# Generated by Django 5.1.4 on 2025-01-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strana', models.CharField(max_length=100)),
                ('gorod', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pasport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=100)),
                ('imya', models.CharField(max_length=100)),
                ('otchestvo', models.CharField(max_length=100)),
                ('data_rojdenia', models.DateField()),
                ('seria', models.IntegerField()),
                ('nomer', models.IntegerField()),
                ('data_vidachi', models.DateField()),
                ('organ_vidachi', models.CharField(max_length=255)),
                ('scan_pasporta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opisanie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zagranpasport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('data_vidachi', models.DateField()),
                ('organ_vidachi', models.CharField(max_length=255)),
                ('data_okonchania', models.DateField()),
                ('scan_zagranpasporta', models.CharField(max_length=255)),
            ],
        ),
    ]
