# Generated by Django 5.1.4 on 2025-01-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('strana', 'gorod')},
        ),
    ]
