# Generated by Django 5.1.4 on 2025-01-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DannieAutorizatsii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_telephona', models.CharField(max_length=15)),
                ('rabochiy_nomer_telephona', models.CharField(max_length=15, null=True)),
                ('rabochiy_emale', models.CharField(max_length=255, null=True)),
                ('emale', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turizm_core.role')),
            ],
        ),
        migrations.CreateModel(
            name='Otel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=100)),
                ('opisanie', models.TextField()),
                ('kolichestvo_zvezd', models.IntegerField()),
                ('osobennosti', models.TextField()),
                ('photo', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turizm_core.address')),
            ],
        ),
        migrations.CreateModel(
            name='Polzovatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registatsii', models.DateField(auto_now_add=True)),
                ('dannie_autorizatsii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turizm_core.dannieautorizatsii')),
                ('pasport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turizm_core.pasport')),
                ('zagranpasport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turizm_core.zagranpasport')),
            ],
        ),
        migrations.CreateModel(
            name='Turoperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=20)),
                ('kpp', models.CharField(max_length=20)),
                ('nazvanie_companii', models.CharField(max_length=255)),
                ('dannie_autorizatsii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turizm_core.dannieautorizatsii')),
            ],
        ),
    ]
