# Generated by Django 5.1.4 on 2025-01-26 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0002_alter_address_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turizm_core.polzovatel'),
        ),
    ]
