# Generated by Django 5.1.4 on 2025-01-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0002_dannieautorizatsii_otel_polzovatel_turoperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Putevka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vremya_otpravlenia', models.DateTimeField()),
                ('data_vremya_vozvrashenia', models.DateTimeField()),
                ('stoimost', models.IntegerField()),
                ('data_vremya_zaselenia', models.DateTimeField()),
                ('data_vremya_viselenia', models.DateTimeField()),
                ('otel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turizm_core.otel')),
                ('turoperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turizm_core.turoperator')),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sozdania', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('dop_info', models.TextField()),
                ('putevka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turizm_core.putevka')),
            ],
        ),
        migrations.CreateModel(
            name='ZakazPolzovatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_dogovora', models.TextField()),
                ('nomer_bileta_tuda', models.CharField(max_length=100)),
                ('nomer_bileta_obratno', models.CharField(max_length=100)),
                ('polzovatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turizm_core.polzovatel')),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turizm_core.zakaz')),
            ],
        ),
    ]
