# Generated by Django 5.1.4 on 2025-01-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0003_putevka_zakaz_zakazpolzovatel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dannieautorizatsii',
            name='emale',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dannieautorizatsii',
            name='nomer_telephona',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
