# Generated by Django 5.1.4 on 2025-01-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0003_zakaz_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasport',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='pasport',
            name='imya',
        ),
        migrations.RemoveField(
            model_name='pasport',
            name='otchestvo',
        ),
        migrations.AddField(
            model_name='polzovatel',
            name='familia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='polzovatel',
            name='imya',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='polzovatel',
            name='otchestvo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
