# Generated by Django 5.1.4 on 2025-01-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0004_remove_pasport_familia_remove_pasport_imya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polzovatel',
            name='familia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polzovatel',
            name='imya',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polzovatel',
            name='otchestvo',
            field=models.CharField(max_length=100),
        ),
    ]
