# Generated by Django 5.1.4 on 2025-01-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0004_alter_dannieautorizatsii_emale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otel',
            name='photo',
            field=models.ImageField(upload_to='otels'),
        ),
    ]
