# Generated by Django 5.1.4 on 2025-01-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0005_alter_otel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasport',
            name='scan_pasporta',
            field=models.ImageField(upload_to='pasports'),
        ),
        migrations.AlterField(
            model_name='role',
            name='opisanie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zagranpasport',
            name='scan_zagranpasporta',
            field=models.ImageField(upload_to='zagranpasports'),
        ),
        migrations.AlterField(
            model_name='zakazpolzovatel',
            name='scan_dogovora',
            field=models.ImageField(upload_to='dogovors'),
        ),
    ]
