# Generated by Django 5.1.4 on 2025-01-26 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0005_alter_polzovatel_familia_alter_polzovatel_imya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polzovatel',
            name='dannie_autorizatsii',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
