# Generated by Django 5.1.4 on 2025-01-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0006_alter_pasport_scan_pasporta_alter_role_opisanie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='opisanie',
            field=models.TextField(),
        ),
    ]
