# Generated by Django 5.1.4 on 2025-01-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0007_alter_role_id_alter_role_opisanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dannieautorizatsii',
            name='rabochiy_emale',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dannieautorizatsii',
            name='rabochiy_nomer_telephona',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
