# Generated by Django 5.1.4 on 2025-01-13 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizm_core', '0008_alter_dannieautorizatsii_rabochiy_emale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polzovatel',
            name='pasport',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turizm_core.pasport'),
        ),
        migrations.AlterField(
            model_name='polzovatel',
            name='zagranpasport',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turizm_core.zagranpasport'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='dop_info',
            field=models.TextField(default=''),
        ),
    ]
